export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const LOCATION_SUCCESS = "LOCATION_SUCCESS";
export const LOCATION_FAIL = "LOACTION_FAIL";
export const LOCATION_DATA_SUCCESS = "LOCATION_DATA_SUCCESS";
export const LOCATION_DATA_FAIL = "LOCATION_DATA_FAIL";
export const LOCATION_DELETE_SUCCESS = "LOCATION_DATA_FAIL";
export const LOCATION_DELETE_FAIL = "LOCATION_DATA_FAIL";

export const ADD_ROOM_SUCCESS = "ADD_ROOM_SUCCESS";
export const ADD_ROOM_FAIL = "ADD_ROOM_FAIL";
export const CREATE_ROOM_SUCCESS = "CREATE_ROOM_SUCCESS";
export const CREATE_ROOM_FAIL = "CREATE_ROOM_FAIL";

export const CREATE_PROFILE = "CREATE_PROFILE";
export const CREATE_PROFILE_ERROR = "CREATE_PROFILE_ERROR";
